title: Portafolio
description: Portfolio ML + Hacking
subtitle: Álex Pasalamar Serrano
logo: /images/icono_hacking.png
favicon: /images/icono_hacking.png

sass:
  sass_dir: _sass
  style: compressed

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    sort_by: date
  writeups:
    output: true
    sort_by: date
