title: Portafolio - Álex
description: Portfolio ML + Hacking

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    sort_by: date
  writeups:
    output: true
    sort_by: date
